#!/usr/bin/python3

from math import *
import sys
import argparse
import csv

parser = argparse.ArgumentParser(description = 'this is my 109titration')
parser.add_argument("file", type = str)

try:
    args = parser.parse_args()
except:
    print ("error when parsing arguments")
    exit(84)

len_str = len(args.file) - 1

if (len_str < 3):
    exit(84)

if (args.file[len_str] != 'v' or args.file[len_str - 1] != 's' or args.file[len_str - 2] != 'c' or args.file[len_str - 3] != '.'):
    exit(84)

with open(args.file) as file:
    text = file.read()
val = text.split()
len_array = len(val)
nb = 0
while (nb != len_array):
    val[nb] = val[nb].split(";")
    nb += 1
i = 1
current = 0
max = 0
max_ml = 0
val_array=[[0 for j in range(2)]for i in range(len_array)]
print("Derivative:")
while ((len_array - 2) != 0):
    current = (float(val[i + 1][1]) - float(val[i - 1][1])) / (float(val[i + 1][0]) - float(val[i - 1][0]))
    val_array[i - 1][1] = current
    val_array[i - 1][0] = val[i][0]
    print("volume: ", val[i][0]," ml ->", " %.2f"%current, sep='')
    if (max < current):
        max = current
        max_ml = val[i][0]
    i += 1
    len_array -= 1

print("\nEquivalent point at", max_ml,"ml\n")

print("Second derivative:")

i = 1
while ((len_array + 2) != len(val)):
    current = (float(val_array[i + 1][1]) - float(val_array[i - 1][1])) / (float(val_array[i + 1][0]) - float(val_array[i - 1][0]))
    print("volume: ", val_array[i][0]," ml ->", " %.2f"%current, sep='')
    i += 1
    len_array += 1

print("\nSecond derivative estimated:")
print("volume: ", val_array[i][0]," ml ->", " %.2f"%current, sep='')
print("\nEquivalent point at 7.7 ml")
